name: watai_hammingai_project
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - arrow-cpp=16.1.0
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - datasets=2.19.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - huggingface_hub=0.24.6
  - icu=73.1
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - multiprocess=0.70.15
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - ply=3.11
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=16.1.0
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytz=2024.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - s2n=1.3.27
  - seaborn=0.13.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.8
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.0
      - attrs==24.2.0
      - click==8.1.7
      - distro==1.9.0
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - litellm==1.48.11
      - markupsafe==2.1.5
      - multidict==6.1.0
      - openai==1.51.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.9.11
      - rpds-py==0.20.0
      - sniffio==1.3.1
      - tiktoken==0.8.0
      - tokenizers==0.20.0
      - typing-extensions==4.12.2
      - yarl==1.13.1
